<?php
/**
 * Student CRUD class.
 *
 * @package School_Management_System
 */

namespace School_Management_System;

/**
 * Student CRUD class
 */
class Student {

	/**
	 * Add a new student.
	 *
	 * @param array $student_data Student data.
	 * @return int|false Student ID on success, false on failure.
	 */
	public static function add( $student_data ) { 
		// No required field validation - all fields are optional
		// Missing data will be auto-generated by the enrollment handler

		if ( self::get_by_roll_number( $student_data['roll_number'] ) ) {
			return new \WP_Error( 'duplicate_roll_number', __( 'A student with this roll number already exists.', 'school-management-system' ) );
		}

		// Create WordPress user if user_id not provided.
		if ( empty( $student_data['user_id'] ) ) {
			$user_id = self::create_user( $student_data );
			if ( is_wp_error( $user_id ) ) {
				return $user_id;
			}
			$student_data['user_id'] = $user_id;
		}

		// Set default enrollment date if not provided.
		if ( empty( $student_data['enrollment_date'] ) ) {
			$student_data['enrollment_date'] = current_time( 'Y-m-d' );
		}

		// Set default status.
		if ( empty( $student_data['status'] ) ) {
			$student_data['status'] = 'active';
		}

		$result = Database::insert( 'students', $student_data );
		
		if ( ! $result ) {
			global $wpdb;
			// Self-healing: If table doesn't exist, try to create it.
			if ( strpos( $wpdb->last_error, "doesn't exist" ) !== false ) {
				if ( ! class_exists( 'School_Management_System\\Activator' ) ) {
					require_once SMS_PLUGIN_DIR . 'includes/class-activator.php';
				}
				Activator::activate();
				$result = Database::insert( 'students', $student_data );
			}
		}
		
		return $result;
	}

	/**
	 * Get student by ID.
	 *
	 * @param int $student_id Student ID.
	 * @return object|null Student object or null if not found.
	 */
	public static function get( $student_id ) {
		return Database::get_row( 'students', array( 'id' => $student_id ) );
	}

	/**
	 * Get student by roll number.
	 *
	 * @param string $roll_number Roll number.
	 * @return object|null Student object or null if not found.
	 */
	public static function get_by_roll_number( $roll_number ) {
		return Database::get_row( 'students', array( 'roll_number' => $roll_number ) );
	}

	/**
	 * Get student by user ID.
	 *
	 * @param int $user_id WordPress user ID.
	 * @return object|null Student object or null if not found.
	 */
	public static function get_by_user_id( $user_id ) {
		return Database::get_row( 'students', array( 'user_id' => $user_id ) );
	}

	/**
	 * Get all students.
	 *
	 * @param array $filters Filter parameters.
	 * @param int   $limit   Number of records per page.
	 * @param int   $offset  Number of records to skip.
	 * @return array Array of student objects.
	 */
	public static function get_all( $filters = array(), $limit = 10, $offset = 0 ) {
		return Database::get_results( 'students', $filters, 'id', 'DESC', $limit, $offset );
	}

	/**
	 * Update student.
	 *
	 * @param int   $student_id Student ID.
	 * @param array $student_data Updated student data.
	 * @return int|false Number of rows updated or false on failure.
	 */
	public static function update( $student_id, $student_data ) {
		if ( empty( $student_id ) ) {
			return false;
		}

		return Database::update( 'students', $student_data, array( 'id' => $student_id ) );
	}

	/**
	 * Delete student.
	 *
	 * @param int $student_id Student ID.
	 * @return int|false Number of rows deleted or false on failure.
	 */
	public static function delete( $student_id ) {
		if ( empty( $student_id ) ) {
			return false;
		}

		// Delete related records.
		Database::delete( 'enrollments', array( 'student_id' => $student_id ) );
		Database::delete( 'attendance', array( 'student_id' => $student_id ) );
		Database::delete( 'fees', array( 'student_id' => $student_id ) );
		Database::delete( 'results', array( 'student_id' => $student_id ) );

		return Database::delete( 'students', array( 'id' => $student_id ) );
	}

	/**
	 * Count total students.
	 *
	 * @param array $filters Filter parameters.
	 * @return int Total number of students.
	 */
	public static function count( $filters = array() ) {
		return Database::count( 'students', $filters );
	}

	/**
	 * Create WordPress user for student.
	 *
	 * @param array $student_data Student data.
	 * @return int|false User ID on success, false on failure.
	 */
	private static function create_user( $student_data ) { 
		$email = sanitize_email( $student_data['email'] );

		// Check if email already exists.
		if ( email_exists( $email ) ) {
			return new \WP_Error( 'email_exists', __( 'A user with this email address already exists.', 'school-management-system' ) );
		}

		$username = sanitize_user( strtolower( $student_data['first_name'] . '.' . $student_data['last_name'] ) );

		// Make username unique.
		$counter = 1;
		$original_username = $username;
		while ( username_exists( $username ) ) {
			$username = $original_username . $counter;
			$counter++;
		}

		$password = wp_generate_password();

		$user_data = array(
			'user_login' => $username,
			'user_email' => $email,
			'user_pass'  => $password,
			'first_name' => $student_data['first_name'],
			'last_name'  => $student_data['last_name'],
		);

		$user_id = wp_insert_user( $user_data );

		if ( is_wp_error( $user_id ) ) {
			return $user_id;
		}

		// Assign student role.
		$user = new \WP_User( $user_id );
		$user->set_role( 'sms_student' );

		// Store password for display to admin.
		update_user_meta( $user_id, 'sms_temp_password', $password );

		return $user_id;
	}

	/**
	 * Search students.
	 *
	 * @param string $search_term Search term.
	 * @return array Array of matching students.
	 */
	public static function search( $search_term ) {
		global $wpdb;

		$students_table    = $wpdb->prefix . 'sms_students';
		$enrollments_table = $wpdb->prefix . 'sms_enrollments';
		$classes_table     = $wpdb->prefix . 'sms_classes';
		$like_term         = '%' . $wpdb->esc_like( $search_term ) . '%';

		$sql = $wpdb->prepare(
			"SELECT DISTINCT s.*, c.class_name FROM $students_table s
			LEFT JOIN $enrollments_table e ON s.id = e.student_id
			LEFT JOIN $classes_table c ON e.class_id = c.id
			WHERE s.first_name LIKE %s 
			OR s.last_name LIKE %s 
			OR s.email LIKE %s
			OR s.roll_number LIKE %s
			OR c.class_name LIKE %s
			OR c.class_code LIKE %s
			ORDER BY s.first_name ASC",
			$like_term,
			$like_term,
			$like_term,
			$like_term,
			$like_term,
			$like_term
		);

		return $wpdb->get_results( $sql );
	}

	/**
	 * Get students by class ID.
	 *
	 * @param int $class_id Class ID.
	 * @return array Array of student objects.
	 */
	public static function get_by_class( $class_id ) {
		global $wpdb;
		$students_table = $wpdb->prefix . 'sms_students';
		$enrollments_table = $wpdb->prefix . 'sms_enrollments';

		$sql = $wpdb->prepare(
			"SELECT DISTINCT s.* FROM $students_table s
			INNER JOIN $enrollments_table e ON s.id = e.student_id
			WHERE e.class_id = %d AND s.status = 'active'
			ORDER BY s.first_name ASC",
			$class_id
		);

		return $wpdb->get_results( $sql );
	}
}
